sudo: required

language: scala
scala: 2.11.6
jdk: oraclejdk8

services:
  - docker

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - docker run -d -p 127.0.0.1:9042:9042 cassandra:2.2

install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  - mvn clean test install -U
  # http://suda.pl/build-and-push-docker-images-using-travis/
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME

cache:
  directories:
    - $HOME/.m2
